export const ErrorCodes = {
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_INSUFFICIENT_QUOTA: 'PROVIDER_INSUFFICIENT_QUOTA',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_MALFORMED_RESPONSE: 'PROVIDER_MALFORMED_RESPONSE',
  PROVIDER_LIMIT_EXCEEDED: 'PROVIDER_LIMIT_EXCEEDED',

  NO_AVAILABLE_PROVIDER: 'NO_AVAILABLE_PROVIDER',
  BLIND_FALLBACK_BLOCKED: 'BLIND_FALLBACK_BLOCKED',
  STREAM_FALLBACK_BLOCKED: 'STREAM_FALLBACK_BLOCKED',
  MODEL_ALIAS_MISSING: 'MODEL_ALIAS_MISSING',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_DISABLED: 'PROVIDER_DISABLED',

  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_BACKUP_FAILED: 'CONFIG_BACKUP_FAILED',
  CONFIG_PATCH_FAILED: 'CONFIG_PATCH_FAILED',

  CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
  CREDENTIAL_STORE_ERROR: 'CREDENTIAL_STORE_ERROR',
  CREDENTIAL_REF_INVALID: 'CREDENTIAL_REF_INVALID',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CREDENTIAL_IN_PLAINTEXT: 'CREDENTIAL_IN_PLAINTEXT',
} as const;
